tap "homebrew/bundle"
tap "homebrew/core", "https://mirrors.ustc.edu.cn/homebrew-core.git"
tap "homebrew/services"
# Shell extension to jump to frequently used directories
brew "autojump"
# Get/set bluetooth power and discoverable state
brew "blueutil"
# Core application library for C
brew "glib"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Command-line outline and bitmap font editor/converter
brew "fontforge"
# Platform built on V8 to build network applications
brew "node"
# The React Native CLI tools
brew "react-native-cli"
# Monitors sleep, wakeup, and idleness of a Mac
brew "sleepwatcher", restart_service: true
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Watch files and take action when they change
brew "watchman"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
